version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./public:/app/public
    networks:
      - leetpro

networks:
  leetpro:
    driver: bridge


